name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:
  macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install pyinstaller
      run: |
        pip3 install pyinstaller --disable-pip-version-check

    - name: Move release files
      shell: bash
      run: |
        mv release/* ./
      working-directory: ${{github.workspace}}

    - name: Build
      run: |
        pyinstaller --onefile --exclude-module pygit2 --name build --distpath dist release.py
      working-directory: ${{github.workspace}}

    - name: Prepare Archive
      shell: bash
      run: |
        rm fortunestreetmodding.github.io/_maps/*/*.webp
        mkdir archive
        mkdir archive/fortunestreetmodding.github.io
        mkdir archive/fortunestreetmodding.github.io/_data
        mv fortunestreetmodding.github.io/_maps archive/fortunestreetmodding.github.io/
        mv fortunestreetmodding.github.io/_data/backgrounds.yml archive/fortunestreetmodding.github.io/_data/
        mv files archive/
        mv patches archive/
        mv -t archive/ *.ttf *.sh *.yaml *.yml || true
        mv dist/* archive/
      working-directory: ${{github.workspace}}

    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{github.workspace}}/archive
        filename: ../CustomStreetWorldTour-${{github.event.release.tag_name}}-macos.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}-macos.zip

    - name: Upload as artifact
      uses: actions/upload-artifact@v3
      with:
        name: zip-file
        path: |
          ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}-macos.zip

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install pyinstaller
      run: |
        pip install pyinstaller --disable-pip-version-check

    - name: Move release files
      shell: bash
      run: |
        mv release/* ./
      working-directory: ${{github.workspace}}

    - name: Build
      run: |
        pyinstaller --onefile --exclude-module pygit2 --name build --distpath dist release.py
      working-directory: ${{github.workspace}}

    - name: Prepare Archive
      shell: bash
      run: |
        rm fortunestreetmodding.github.io/_maps/*/*.webp
        mkdir archive
        mkdir archive/fortunestreetmodding.github.io
        mkdir archive/fortunestreetmodding.github.io/_data
        mv fortunestreetmodding.github.io/_maps archive/fortunestreetmodding.github.io/
        mv fortunestreetmodding.github.io/_data/backgrounds.yml archive/fortunestreetmodding.github.io/_data/
        mv files archive/
        mv patches archive/
        mv -t archive/ *.ttf *.bat *.yaml *.yml || true
        mv dist/* archive/
      working-directory: ${{github.workspace}}

    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{github.workspace}}/archive
        filename: ../CustomStreetWorldTour-${{github.event.release.tag_name}}-windows.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}-windows.zip

    - name: Upload as artifact
      uses: actions/upload-artifact@v3
      with:
        name: zip-file
        path: |
          ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}-windows.zip

  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
