name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Archive
      run: |
        cp ./release/* .
        rm fortunestreetmodding.github.io/_maps/*/*.webp
        zip -v CustomStreetWorldTour-${VERSION_NAME}.zip -r files -r patches -r fortunestreetmodding.github.io/_maps build.* *.py requirements.txt
      working-directory: ${{github.workspace}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}.zip
