name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Archive
      run: |
        cp ./release/* .
        rm fortunestreetmodding.github.io/_maps/*/*.webp
        rm *.webp
        rm *.md
        zip -r -v CustomStreetWorldTour-${VERSION_NAME}.zip files/ patches/ fortunestreetmodding.github.io/_maps/ fortunestreetmodding.github.io/_data/backgrounds.yml DejaVuSans-Bold.ttf build.* *.py customStreetWorldTour.yaml requirements.txt
      working-directory: ${{github.workspace}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}.zip

    - name: Upload as artifact
      uses: actions/upload-artifact@v3
      with:
        name: zip-file
        path: |
          ${{github.workspace}}/CustomStreetWorldTour-${{github.event.release.tag_name}}.zip